### ISSUE TITLE
Need to unsubscribe?

### ISSUE THREAD

**Issue by SandLZ** [cristiammercado/ng-event-bus#1]
When using code:
`
eventBus.on('app:start').subscribe((message)=>{
	console.log(message); //will receive 'started' only
});
`
should i unsubscribe?

**Comment by cristiammercado** [comment]
Hi @SandLZ,

Yes, in the scenario that you show it's necessary that you unsubscribe from the observable to avoid memory leaks. That happens because the library exposes an _infinite_ observable. That's no exactly related to the library, but in the way in which the observables works in Rxjs .

However, there're ways that you don't need to unsubscribe, for example if you use `.first()` in the pipe of the observale because using this method would turn it into a finite observable (It would apply in your case because you're just waiting for an one-time event).

I recommend you to read this [stackoverflow answer](https://stackoverflow.com/a/50633482/3144639) about a similar question!

**Comment by SandLZ** [comment]
> Hi @SandLZ,
> 
> Yes, in the scenario that you show it's necessary that you unsubscribe from the observable to avoid memory leaks. That happens because the library exposes an _infinite_ observable. That's no exactly related to the library, but in the way in which the observables works in Rxjs .
> 
> However, there're ways that you don't need to unsubscribe, for example if you use `.first()` in the pipe of the observale because using this method would turn it into a finite observable (It would apply in your case because you're just waiting for an one-time event).
> 
> I recommend you to read this [stackoverflow answer](https://stackoverflow.com/a/50633482/3144639) about a similar question!

Thank you for your reply. Now I know how to do it.
